### ISSUE TITLE
Feedback / Comments

### ISSUE THREAD

**Issue by martinklepsch** [lread/cljdoc-analyzer#1]
Hey @lread — thanks for your interest in working on this, I think we're pretty much on the same page. I tried to add some notes on the various parts you requested feedback on. 

I'm also watching this repository now so feel free to use the issues for anything else that comes up. 

Hope this all makes sense :v: 

--- 

### Questions / Notes 

- I’m ok dropping the `codox` namespace prefix if we also remove any traces from the existing cljdoc codebase. I’ve grown to dislike that some stuff is just called `codox-edn` and the like. We could have more descriptive names that are less linked to an implementation detail (i.e. the fact that we’re using codox).
- Generally integrating stuff back into Codox would be nice but at the same time codox is kind of working as intended and maybe also “done” so this idea of feeding things back into it might not really be that important. 
- The analyser should not skip `no-doc` stuff as you already pointed out. I think we should just return that as is and remove that at either of these two steps:
	- importing data into the database or
	- reading / rendering it
- “just curious, is protocol :members → :type always :var?”
	- I don’t know, is it? 😝 I found the type stuff for `:members` a little confusing at first, I think `:var` might just be the general fallback as well?
- Parallel Support: Not sure what you mean here, `clojure.parallel` failed to load which caused `org.clojure/clojure` to break analysis. Is that what you mean by parallel support?

### Inputs

- `:language` — `:auto-detect` and/or array specification sounds great to me.
	- As an aside: we run stuff once for each language while generally this could also be done in a single run. This is an optimisation that I’ve meant to implement for a long time. 
- `:root-paths` & `:source-paths` — if the problem we’re solving with the analyzer is analysing source files I think we should only provide paths based on the jar root. Everything else can be done by looking at `pom.xml` and I think that’s probably not terribly important.  
- `:namespace` at some point the regex felt necessary but we’ve been fine without it now so I guess fine to skip it. 
- `:exception-handler` — I’d love to see cljdoc handle single namespaces that could not be analyzed more gracefully. Right now a single failed namespace will break the entire API analysis. I would suggest keeping this but not entirely sure if you were suggesting to remove it.
- `:writer`  OK to remove, if people want to call a function on the returned data they can just do that themselves :) 
- `:exclude-vars` I’d keep it around for now, not sure what for but maintenance cost seems low? 

### Outputs

Need to stay backwards compatible as you also noted. I’d be open to have more things in explicit columns but at the same time I’m not seeing a lot of gains.

### Future

> Proposal: I like option #3. It makes cljdoc-analyzer potentially also interesting as an ad hoc tool.

Agree. We could also integrate the various hardcoded fixes for some jars (missing deps etc) and thus have a shared place where the community can document what is needed to analyze a specific jar. 

Generally cljdoc was also always meant to serve this raw analysis data through an API. This isn’t really dependent on the analyser and more on coming up with a nice API around it though.

**Comment by lread** [comment]
Thanks for the very thoughtful feedback @martinklepsch, much appreciated!  I’m sure I’ll be pinging you as I dig in with implementation.

**Comment by lread** [comment]
I think we've captured all of this in either code or new issues @martinklepsch , so closing.
