### ISSUE TITLE
Verify that cljdoc-analyzer works from jar

### ISSUE THREAD

**Issue by lread** [lread/cljdoc-analyzer#10]
I have verified that cljdoc-analyzer works when referenced via git url whi sha in deps.edn.

I have yet to verify that it works when bundled as a jar.

The somewhat unusual thing about cljdoc-analyzer is that it has the internal metagetta subproject.

**Comment by martinklepsch** [comment]
For cljdoc itself using this project via it's Git coordinates is fine for now.

**Comment by lread** [comment]
Did some tests.

Metagetta as a subproject works when referenced by cljdoc-analyzer via:
* `:local/root`
* `:git/url` (after moving metagetta under modules dir)

Not so lucky when cljdoc-analyzer is packaged in a jar. It seems that tools.deps.alpha expect deps to resolve down to the :file protocol. A file in a jar does not use the :file protocol.

Ironicaly, cljdoc-analyzer cannot analyze itself as it tries to parse metagetta source. We could add an option to exclude-dirs from analysis.

I like having metagetta as an internal subproject within cljdoc-analyzer as they are tightly coupled, but if this won't fly for technical reasons, I suppose it could be split out into its own project.

One last test: I will try extracting metagetta out of the jar to a temp dir and referencing it via `:local/root`.

**Comment by lread** [comment]
Did some sanity testing and tweaks.  Can considered fixed by fc0c60d5242588bfd37feeccd8d632d5fb5807c8
