### ISSUE TITLE
Is using an older version of clojure important?

### ISSUE THREAD

**Issue by lread** [lread/cljdoc-analyzer#13]
As I review the changes I have made I notice that the codox fork/branch specified clojure 1.9 as a dep.  

Metagetta specifies latest clojure and clojurescript deps which makes me question deps.clj's work to ensure clojure/clojurescript are included and of recentish versions.  

@martinklepsch do you know/remember of a technical need to ever analyze with older versions of clojure/clojurescript?

I'm guessing the idea was to try to stick with the version of clojure specified by the project being analyzed unless it was just too old?

**Comment by martinklepsch** [comment]
Your guess is about right - as far as I can remember anyways. 😄

**Comment by lread** [comment]
Ok thanks! Closing.
