### ISSUE TITLE
Handle string requires / foreign libs in CLJS

### ISSUE THREAD

**Issue by martinklepsch** [lread/cljdoc-analyzer#5]
Via https://github.com/cljdoc/cljdoc/issues/289

Some libraries like https://github.com/Lokeh/hx require `"react"` to be provided via foreign-libs / npm and analysis for them doesn't work because `"react"` can't be found. I think if we would provide a `deps.cljs` file that claims there is a foreign lib called `"react"` we should be able to get this to work. This assumes that for the analysis the contents of the underlying JS file are irrelevant, which I think is true.

This issue is also somewhat related: https://github.com/cljdoc/cljdoc/issues/297

**Comment by martinklepsch** [comment]
I've added a test for `hx` in a local clone and will investigate this further. Shouldn't be too hard to provide "fake foreign libs" for some common cases like React.

**Comment by martinklepsch** [comment]
Ok, I think I mostly figured this out. (Thanks to @thheller for helping me see my mistake.)

The test in #6 still fails for some reason but will look into that later.

**Comment by thheller** [comment]
Some time ago I already created an example to "fake" string requires. Your code likely changed over time but the basic gist is that you call `ana/parse-ns` first which will tell you which strings were used. You than fake those into the compiler state with a dummy name and then proceed with the actual `analyze` call.

See https://gist.github.com/thheller/5bc57a7571cf83fd12190ab7165cdb46#file-codox-cljs-clj-L87-L91

If I read the "metagetta" code correctly that should maybe happen somewhere arround here? https://github.com/lread/cljdoc-analyzer/blob/master/modules/metagetta/src/cljdoc_analyzer/metagetta/clojurescript.clj#L95

**Comment by lread** [comment]
Closed by d7cb539620dc2e2b910679f16931b7466dc320d5

**Comment by martinklepsch** [comment]
Created a new issue #18 to implement a more general solution, potentially using the approach @thheller suggested. Thanks!
